name: production

on:
  push:
    branches:
      - master

jobs:
  lint:
    uses: spuxx1701/ci/.github/workflows/npm_lint.yml@v1.2

  docker_deploy:
    needs: lint
    uses: spuxx1701/ci/.github/workflows/docker_deploy.yml@v1.2
    with:
      username: spuxx
      repository: doleo-2-client
      environment: integrate
      dockerfile: Dockerfile.integration
    secrets:
      token: ${{ secrets.DOCKERHUB_TOKEN }}
      ssh_host: ${{ secrets.SSH_HOST }}
      ssh_username: ${{ secrets.SSH_USERNAME }}
      ssh_password: ${{ secrets.SSH_PASSWORD }}
