name: pull-request

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  types:
    uses: spuxx1701/ci-cd/.github/workflows/npm_types.yml@v2.1

  lint:
    uses: spuxx1701/ci-cd/.github/workflows/npm_lint.yml@v2.1
