name: staging

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  types:
    uses: spuxx1701/ci-cd/.github/workflows/npm_types.yml@v2.1

  lint:
    uses: spuxx1701/ci-cd/.github/workflows/npm_lint.yml@v2.1

  release_image:
    needs:
      - types
      - lint
    uses: spuxx1701/ci-cd/.github/workflows/release_image.yml@v2.1
    with:
      dockerfile: Dockerfile.staging
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
