name: staging

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  release_image:
    uses: spuxx1701/ci-cd/.github/workflows/docker_release_image.yml@v4.1.0
    timeout-minutes: 60
    with:
      dockerfile: Dockerfile.production
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
